Update build_kernel_op8_nameless15_a15.yml

diff --git a/.github/workflows/build_kernel_op8_nameless15_a15.yml b/.github/workflows/build_kernel_op8_nameless15_a15.yml
--- a/.github/workflows/build_kernel_op8_nameless15_a15.yml
+++ b/.github/workflows/build_kernel_op8_nameless15_a15.yml
@@ -3,8 +3,12 @@ on:
   workflow_call:
   workflow_dispatch:
 env:
-  HOOK_METHOD: "normal" # manual hook method,can choice syscall and normal.
+  HOOK_METHOD: "normal" # manual hook method, can choice syscall and normal.
   HOOK_OLDER: "false" # contain backport older patch and syscall older patch.
+  KPM_ENABLE: "true" # Only use it for SukiSU-Ultra.
+  KPM_FIX: "true" # Fix Error When Enabling KPM.
+  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source
+  REKERNEL_ENABLE: "true" # if u need Re:Kernel.
 
 jobs:
   build:
@@ -46,7 +50,6 @@ jobs:
               BOOT_SOURCE
               LXC_ENABLE
               ROM_TEXT
-
           )
 
           for CONFIG in "${CONFIG_LIST[@]}"; do
@@ -64,12 +67,7 @@ jobs:
         if: env.LXC_ENABLE == 'true'
         uses: jlumbroso/free-disk-space@main
         with:
-          # this might remove tools that are actually needed,
-          # if set to "true" but frees about 6 GB
           tool-cache: true
-
-          # all of these default to true, but feel free to set to
-          # "false" if necessary for your workflow
           android: false
           dotnet: true
           haskell: true
@@ -113,7 +111,6 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE
 
-          # Set GCC Aarch64
           if [ -z "${{ env.GCC_64_SOURCE }}" ]; then
             echo "Not set GCC 64!"
           else
@@ -134,8 +131,6 @@ jobs:
             echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/$GCC_64_BIN" >> $GITHUB_ENV
           fi
 
-
-          # Set GCC ARM32
           if [ -z "${{ env.GCC_32_SOURCE }}" ]; then
             echo "Not set GCC 32!"
           else
@@ -156,7 +151,6 @@ jobs:
             echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/$GCC_32_BIN" >> $GITHUB_ENV
           fi
 
-          # Set Clang
           if [[ "${{ env.CLANG_SOURCE }}" == *".git" ]]; then
             git clone ${{ env.CLANG_SOURCE }} -b ${{ env.CLANG_BRANCH }} clang-custom --depth=1
           elif [[ "${{ env.CLANG_SOURCE }}" == *'.tar.gz' ]]; then
@@ -221,17 +215,17 @@ jobs:
 
       - name: Set Pack Method and KernelSU and SUSFS
         run: |
-          # Variable
           SUSFS_SOURCE=https://gitlab.com/simonpunk/susfs4ksu.git
           SUSFS_BRANCH=kernel-${{ env.KERNEL_VERSION }}
-          PACK_METHOD=Anykernel3 # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
-          KERNELSU_METHOD=shell # shell and manual
+          PACK_METHOD=Anykernel3
+          KERNELSU_METHOD=shell
 
-          # Set $PACK_METHOD and KernelSU
           if [[ $PACK_METHOD == "Anykernel3" ]]; then
             cd $GITHUB_WORKSPACE/device_kernel
             if [[ -d "Anykernel3" ]]; then
-              echo "Found Anykernel3 in Kernel!"
+              echo "Found Anykernel3 in Kernel
+
+!"
             else
               git clone ${{ env.AK3_SOURCE }} -b ${{ env.AK3_BRANCH }} Anykernel3 --depth=1
             fi
@@ -246,19 +240,13 @@ jobs:
           echo "PACK_METHOD=$PACK_METHOD" >> $GITHUB_ENV
 
           if [[ $KERNELSU_METHOD == "shell" ]]; then
-            # Construct the full URL to the setup script
             if [[ "${{ env.KERNELSU_SOURCE }}" == *"/setup.sh" ]]; then
-              # URL already contains the script path
               KERNELSU_SCRIPT_URL="${{ env.KERNELSU_SOURCE }}"
             else
-              # Append the script path
               KERNELSU_SCRIPT_URL="${{ env.KERNELSU_SOURCE }}/${{ env.KERNELSU_BRANCH }}/kernel/setup.sh"
             fi
-            
             echo "KernelSU Script URL: $KERNELSU_SCRIPT_URL"
             echo "KernelSU Branch: ${{ env.KERNELSU_BRANCH }}"
-            
-            # Download and execute the script with error handling
             SCRIPT_CONTENT=$(curl -sSL "$KERNELSU_SCRIPT_URL")
             if [ $? -eq 0 ] && [ -n "$SCRIPT_CONTENT" ]; then
               echo "$SCRIPT_CONTENT" | bash -s ${{ env.KERNELSU_BRANCH }}
@@ -280,12 +268,11 @@ jobs:
           KSU_VERSION=$(cd ${{ env.KERNELSU_NAME }} && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
 
-          # Set SUSFS
           if [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
             if [[ "${{ env.SUSFS_FIXED }}" == true ]]; then
               PATCHES_SOURCE=JackA1ltman/NonGKI_Kernel_Patches
               PATCHES_BRANCH=op_kernel
-              git clone https://github.com/$PATCHES_SOURCE.git -b $PATCHES_BRANCH NonGKI_Kernel_Patches --depth=1 # It's not necessary.
+              git clone https://github.com/$PATCHES_SOURCE.git -b $PATCHES_BRANCH NonGKI_Kernel_Patches --depth=1
             fi
             git clone $SUSFS_SOURCE -b $SUSFS_BRANCH susfs4ksu --depth=1
             cp susfs4ksu/kernel_patches/fs/* fs/
@@ -293,6 +280,25 @@ jobs:
           else
             echo "Disabled SUSFS !"
           fi
+
+          # Set KPM
+          if [[ "${{ env.KPM_ENABLE }}" == "true" ]]; then
+            if [ -f "include/linux/set_memory.h" ]; then
+              echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+              wget "${{ env.KPM_PATCH_SOURCE }}" -O patch
+              chmod a+x patch
+              echo "Set KPM successfully !"
+            else
+              echo "Your kernel does not support KPM, missing set_memory.h"
+            fi
+          fi
+
+      - name: Fix Error When Enabling KPM
+        if: env.KPM_ENABLE == 'true' && env.KPM_FIX == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/${{ env.KERNELSU_NAME }}/kernel/kpm
+          cp /tmp/Patches/Patch/fix_kpm.patch ./
+          patch -p1 < fix_kpm.patch || true
 
       - name: Patch Kernel for no-kprobe
         run: |
@@ -352,7 +358,6 @@ jobs:
 
       - name: Extra Kernel Options
         run: |
-          # Only ${{ env.DEVICE_NAME }} use it.
           cd $GITHUB_WORKSPACE/device_kernel
           echo "CONFIG_KASAN_STACK_ENABLE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
           echo "CONFIG_LTO_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
@@ -367,34 +372,25 @@ jobs:
       - name: Disable Kprobes Configuration
         run: |
           cd $GITHUB_WORKSPACE/device_kernel
-          
-          # List of kprobes-related configs to disable
           KPROBES_CONFIGS=(
             "CONFIG_KPROBES"
             "CONFIG_HAVE_KPROBES"
             "CONFIG_KPROBE_EVENTS"
             "CONFIG_KPROBE_EVENT"
           )
-          
-          # Process each config
           for config in "${KPROBES_CONFIGS[@]}"; do
-            # Check if config exists in defconfig
             if grep -q "^${config}=" ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}; then
-              # Config exists, replace it with =n
               sed -i "s/^${config}=.*/${config}=n/" ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
               echo "Updated existing ${config} to n"
-            elif grep -q "^# ${config} is not set" ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}; then
-              # Config already disabled, no change needed
+            elif grep -q "^# ${config} is not set" ./arch/arm有什么/configs/${{ env.DEFCONFIG_NAME }}; then
               echo "${config} is already disabled"
             else
-              # Config doesn't exist, add it as disabled
               echo "${config}=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
               echo "Added ${config}=n to defconfig"
             fi
           done
-          
           echo "Kprobes configuration disabled successfully!"
-          
+
       - name: Setup LXC
         if: env.LXC_ENABLE == 'true'
         run: |
@@ -402,28 +398,19 @@ jobs:
           rm -rf lxc
           git clone https://github.com/tomxi1997/lxc-docker-support-for-android.git lxc
           echo 'source "lxc/Kconfig"' >> "Kconfig"
-
           echo "CONFIG_DOCKER=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-
           sed -i '/CONFIG_ANDROID_PARANOID_NETWORK/d' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
           echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-
-          #sed -i '/CONFIG_LOCALVERSION/d' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          #echo 'CONFIG_LOCALVERSION="-LXC"' >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-
           chmod +x $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh
           if [ -f $GITHUB_WORKSPACE/device_kernel/kernel/cgroup/cgroup.c ]; then
               sh $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh $GITHUB_WORKSPACE/device_kernel/kernel/cgroup/cgroup.c
           fi
-
           if [ -f $GITHUB_WORKSPACE/device_kernel/kernel/cgroup.c ]; then
               sh $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh $GITHUB_WORKSPACE/device_kernel/kernel/cgroup.c
           fi
-
           if [ -f $GITHUB_WORKSPACE/device_kernel/net/netfilter/xt_qtaguid.c ]; then
               patch -p0 < $GITHUB_WORKSPACE/device_kernel/lxc/xt_qtaguid.patch
           fi
-
           echo "LXC_ENABLE=lxc" >> $GITHUB_ENV
 
       - name: Patch Kernel of SUSFS
@@ -431,9 +418,7 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/device_kernel/
           cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-$KERNEL_VERSION.patch ./
-
           patch -p1 < 50_add_susfs_in_kernel-${{ env.KERNEL_VERSION }}.patch || true
-
           if [[ "${{ env.KERNELSU_NAME }}"  == "KernelSU-Next" ]]; then
             if [[ "${{ env.KERNELSU_SOURCE }}" =~ ".sh" && "${{ env.KERNELSU_BRANCH }}" =~ "susfs" ]]; then
                 echo "KernelSU-Next SuSFS Branch detected!"
@@ -441,10 +426,6 @@ jobs:
                 git clone ${{ env.KERNELSU_SOURCE }} -b ${{ env.KERNELSU_BRANCH }}-susfs susfs_fixed
                 rsync -av --exclude='.git' susfs_fixed/kernel/ KernelSU-Next/kernel/
             fi
-          elif [[ "${{ env.KERNELSU_SUS_PATCH }}" == "true" ]]; then
-            cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./${{ env.KERNELSU_NAME }}
-            cd ${{ env.KERNELSU_NAME }}
-            patch -p1 < 10_enable_susfs_for_ksu.patch || true
           fi
 
       - name: Fixed Kernel Patch
@@ -453,14 +434,10 @@ jobs:
           cd $GITHUB_WORKSPACE/device_kernel/
           cp NonGKI_Kernel_Patches/kona_oos/namespace_fixed.patch ./
           cp NonGKI_Kernel_Patches/kona_oos/task_mmu_fixed.patch ./
-
           patch -p1 < namespace_fixed.patch || true
           patch -p1 < task_mmu_fixed.patch || true
-
-          # Upgrade SUSFS Version
           cp /tmp/Patches/Patch/susfs_upgrade_to_157.patch ./
           cp NonGKI_Kernel_Patches/kona_oos/susfs_upgrade_fixed.patch ./
-
           patch -p1 < susfs_upgrade_to_157.patch || true
           patch -p1 < susfs_upgrade_fixed.patch || true
 
@@ -469,13 +446,20 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/device_kernel/
           cp /tmp/Patches/Patch/susfs_upgrade_to_157.patch ./
-
           patch -p1 < susfs_upgrade_to_157.patch || true
 
-          # Extra SUSFS Patch
-          # cp NonGKI_Kernel_Patches/[patch_folder]/[patch_file].patch ./
-
-          # patch -p1 < [patch_file].patch || true
+      - name: Patch Kernel of Re:Kernel
+        if: env.REKERNEL_ENABLE == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+          PATCH_FILE="/tmp/Patches/Rekernel/rekernel-${{ env.KERNEL_VERSION }}.patch"
+          if [ -f "$PATCH_FILE" ]; then
+            cp /tmp/Patches/Rekernel/rekernel-${{ env.KERNEL_VERSION }}.patch ./
+            patch -p1 < rekernel-${{ env.KERNEL_VERSION }}.patch || true
+            echo "Re:Kernel Patched."
+          else
+            echo "Your kernel not supported it."
+          fi
 
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
@@ -495,16 +479,42 @@ jobs:
             make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
           fi
 
+      - name: KPM Patcher
+        if: env.KPM_ENABLE == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel
+          if [ -f "patch" ]; then
+            IMAGE_DIR="out/arch/arm64/boot"
+            if [ -f "$IMAGE_DIR/Image.gz" ]; then
+              cd "$IMAGE_DIR"
+              gunzip Image.gz
+              cp ../../patch ./
+              ./patch
+              mv oImage Image
+              gzip Image
+              echo "Patched Image.gz for KPM"
+            elif [ -f "$IMAGE_DIR/Image" ]; then
+              cd "$IMAGE_DIR"
+              cp ../../patch ./
+              ./patch
+              mv oImage Image
+              echo "Patched Image for KPM"
+            else
+              echo "No Image or Image.gz found, cannot patch for KPM"
+              exit 1
+            fi
+          else
+            echo "KPM patch script not found"
+            exit 1
+          fi
+
       - name: Make Anykernel3 Flasher
         if: env.PACK_METHOD == 'Anykernel3'
         run: |
           IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
           TIME=$(date +"%Y%m%d%H%M%S")
-
           cd $GITHUB_WORKSPACE/device_kernel/
-
           mkdir -p tmp
-
           if [[ "${{ env.AK3_SOURCE }}" =~ "osm0sis" ]]; then
             sed -i 's/do.devicecheck=1/do.devicecheck=0/g' Anykernel3/anykernel.sh
             sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' Anykernel3/anykernel.sh
@@ -513,7 +523,6 @@ jobs:
           else
             echo "Now using custom Anykernel3."
           fi
-
           if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
             cp -fp $IMAGE_DIR/Image.gz-dtb tmp
             echo "Found Image.gz-dtb !"
@@ -525,28 +534,24 @@ jobs:
             cp -fp $IMAGE_DIR/Image.gz tmp
             echo "Found Image ! Automatic convert Image.gz ! "
           fi
-
           if [[ -f "$IMAGE_DIR/dtbo.img" ]]; then
             cp -fp $IMAGE_DIR/dtbo.img tmp
             echo "Found dtbo.img !"
           else
             echo "Doesn't found dtbo.img! Your device maybe needn't the file."
           fi
-
           if [ -f "$IMAGE_DIR/dtb" ]; then
             echo "Found DTB!"
             cp -fp $IMAGE_DIR/dtb tmp
           else
             echo "Doesn't found DTB! Your device maybe needn't the file."
           fi
-
           cp -rp ./Anykernel3/* tmp
           cd tmp
           7za a -mx9 tmp.zip *
           cd ..
           cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip
           rm -rf tmp
-
           echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip" >> $GITHUB_ENV
 
       - name: Make Latest Boot Image
@@ -556,9 +561,7 @@ jobs:
           IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
           TIME=$(date +"%Y%m%d%H%M%S")
           FORMAT_MKBOOTING=$(echo `mkboottools/unpack_bootimg.py --boot_img=boot_source_${{ env.DEVICE_NAME }}.img --format mkbootimg`)
-
           mkboottools/unpack_bootimg.py --boot_img boot_source_${{ env.DEVICE_NAME }}.img
-
           if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
             rm -f out/kernel
             cp -fp $IMAGE_DIR/Image.gz-dtb out/kernel
@@ -573,11 +576,8 @@ jobs:
             cp -fp $IMAGE_DIR/Image.gz out/kernel
             echo "Found Image ! Automatic convert Image.gz ! "
           fi
-
           eval "mkboottools/mkbootimg.py $FORMAT_MKBOOTING -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img"
-
           echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img" >> $GITHUB_ENV
-
           rm -f $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
 
       - name: Upload Build Artifacts
